### ISSUE TITLE
Creating a python version of the script

### ISSUE THREAD

**Issue by SuchitReddi** [SuchitReddi/memorywipe#5]
To make the script compatible with different operating systems other than linux, a python version of the tool is required.
os.system can be used to achieve this.

**Comment by p1utoze** [comment]
Thanks for accepting my request @SuchitReddi and also for the resources. 
Definitely want to contact further but there's a slight issue in joining your slack workspace. I'm unable to access it.

**Comment by SuchitReddi** [comment]
https://join.slack.com/t/opensrcmemorywipe/shared_invite/zt-28olrjb9t-0k61qROOR8SHwBdbUZLf5g

This is a new link, valid for a month. Please try this.

**Comment by p1utoze** [comment]
This link works. Finally could join in. Thanks for helping me out @SuchitReddi
